version: '3'
services:
  countdown-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data/countdown
    container_name: countdown-viewer
    stdin_open: true  # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data/countdown
    container_name: countdown-data-generator
    command: conda run -n zero python /app/experiments/continual/data_gen.py

  continual-trainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data/countdown
      - ./wandb:/app/wandb  # For WandB logs
      - ./logs:/app/logs    # For training logs
    container_name: countdown-continual-trainer
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - BASE_MODEL=/app/models/base_model.pt  # Set your base model path
      - N_GPUS=4
      - ROLLOUT_TP_SIZE=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: conda run -n zero bash /app/scripts/train_continual_countdown.sh
